language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: dFTAWT5aw9NF05xTJeuvFa7gnZHsRgaew6/ipg7aijud7SGMdXWyZT5ZODi72Kgegkryz+Lmr7kdbXhab4FfeVMwp8yEfsznfziEcm+lcn0KNaTDfZryznahS+xPC3hsCqegGi4UccrhtLynLJ+djzDCa3ZGzJlyWWcaWhHoo/e0uqpYaLqPQi2sPuCq1mFNhUY+mo/iiaOKvUbAiuAQzkYiBfn1slUcBUWC5ZQSFTiRFdGub4i0EH5RMFm5TlSR8y9UixKptS84vxXseQDbo78IOO/Yz4mc3SEqmnkihfP0XskeILgYYXgjJ2v3iX5+GUfZTsk2+xptp4uoS3pp2U1DMMjsyzke8jY9RJwTDl0bAUoiI2gEJQtTjY9XLCuBvJqNYXy7ebxnyotvr6glUqblIOG0SZKms1/kx3zQn48nym5ryIuxHYMVuZfkEjMzN4YB+QOqwcnkdrxxg6/YXBxzLY0sRWXDGr+w0qxxOxpCg5iQtgHcFiomFuLxr/O7KkvdnMoF2AfyfTZEiCLlilsF+BgUEmaS9dhwZ5eIanDjj7IM7oXBLTGE1Z/6zdJrGaKigo4mBFJ1yIPd90sUAkwACeCcLBqqcvul0hoSQAyR1KJfBRqDyibZDmvxDYgAfbr1Sr4slIi7Qb0NDdgauQdl6efhyEafTTOngj5G+bQ=
  app: nameless-plateau-59710.herokuapp
  on:
    repo: jbvance/node-shopping-list-integration-tests
