language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: B9PmH3aLqImhN1qTRHkM87KlX8FgX7BlUbEf7JJlkXhRSlA20atcTvPJu5wNoBHdtuuiiF+sww6/5N+tUE1ckKIJTUEgtaohK4ZEjx6pK2BH/3QxSJRvMwNl2JMlWowbvgRi253sD2A4m+6jU/TW/RemWvEqrkHqjDba5XfmwNZYA5HRcdV8VTGjnfhVCfxo5qJgGX5O2VDRq1Okf1tEc+Rg1VxHUSNIqoBgirdsU7KsLiqdVeWLQzkkv6VX3LUt14JuUA0zSyWG39qBlyiDlcdDOcDzTHBrk1wrJSqs4FAEY/rJ8Dd484C3CYJyv+w46sTv4UmSY1IWIuiJh2Kngj1+jfgWL7enTdFmczrq0E0wEYDEvGCNFArQi0PzsOiILsQIX9v3vnAbRJYjjkcfjdFEW1zD1pC+/Q1vhmW5HI84nEQigx5p7aYmXmYjJ8EEBzw1Hr/qBXmgu09v+83OCVHBLweRkVJrae+bIVX6M0AwghGoOHTMrkuJfA3r31N6rmTnRxig98XPFjrbdr3GDq1YX710cGZxZBHuVxDjrIV51F7HuQ0iqUmG+c/LFXeXA9l3wEKNq5LKRHDBxwm9sQVPqX88C+/02xM6GHNEcvCLDaa/aXKGCoyu0STO2ltTBovXvAMhMNgNTm3h6kLUyKNdqEa+WcmcMFSNqvBtVj0=
  app: enigmatic-tundra-35643.herokuapp.com
  on:
    repo: jbvance/node-shopping-list-integration-tests
